#!/bin/bash
cd ~/.dotfiles
if [ -d ~/.dotfiles ]; then
	#	set up the shell environment
	for file in ~/.dotfiles/enabled/*; do
		[ -r "$file" ] && source "$file"
	done
	#	home dir files
	for dotfile in `find ~/.dotfiles/home -type f`; do
		if [ -r "$dotfile" ]; then

			localfile=${dotfile/\/\.dotfiles\/home}
			archivedir=~/.dotfiles/archive/"$(git rev-parse HEAD)"/home
			archivefile=$archivedir/"$(basename $localfile)"

			if [ -h "$localfile" ] && [ `readlink $localfile` == "$dotfile" ]; then
				x=5;
				# the file exists but is not a real file
			else
				mkdir -p $archivedir
				if [ -r $localfile ]; then
					mv $localfile $archivefile
				fi
				ln -s $dotfile $localfile
			fi
		fi
	done
	#	delete broken symlinks
	#	@TODO fix this warning
	#	find: warning: you have specified the -maxdepth option after a non-option argument -type, but options are not positional (-maxdepth affects tests specified before it as well as those specified after it).  Please specify options before other arguments.
	find ~ -maxdepth 1 -type l ! -exec test -r {} \; -delete
fi
cd $OLDPWD
#	cleanup
unset file
unset dotfile
unset localfile
unset archivefile
unset archivedir
unset x
