#!/bin/bash

alias ll='ls -alFGh'
alias l='ls -cGFh'
alias g='git'
alias t='funky-terminal'
alias ks='ls'
alias gs='git status'
alias o='xdg-open'

EDITOR='nvim'
export EDITOR
alias nano='nvim'

alias sis="systemctl --user"
