#!/bin/bash

alias ll='ls -alFG'
alias la='ls -AG'
alias l='ls -GF'
alias b2d='if [ $(boot2docker status) != "running" ]; then boot2docker up; fi; eval "$(boot2docker shellinit)"'
alias g='git'
alias d='docker'
alias quicklook='qlmanage -p 2>/dev/null'
alias dotfiles_reload='source ~/.dotfiles/bootstrap'