#!/bin/bash

ALTUM_HOME=~/repos/altum

source $ALTUM_HOME/integration-devtools/environment/altum/build/local/etc_profiled

function start_server() {
	#nohup $ALTUM_HOME/integration-devtools/scripts/localdev/start_server 1> $ALTUM_HOME/logz/server.out.log 2> $ALTUM_HOME/logz/server.err.log & disown
	$ALTUM_HOME/integration-devtools/scripts/localdev/start_server.sh
};

function start_client() {
	$ALTUM_HOME/integration-devtools/scripts/localdev/start_client.sh
};

function open_tunnel() {
	ssh -N -T -f ujump
};

function close_tunnel() {
	echo 'close_tunnel() is not written yet. why not write it now?';
};

