#!/bin/bash

## https://sanctum.geek.nz/arabesque/better-bash-history

shopt -s histappend
HISTFILESIZE=1000000
HISTSIZE=1000000
HISTCONTROL=ignoreboth
HISTIGNORE='ls:bg:fg:history:sybil'
HISTTIMEFORMAT='%F %T '
shopt -s cmdhist

##	this seems like a bad idea
#PROMPT_COMMAND='history -a'

