#!/bin/bash

#   now you can enable bash completion per-module
#   @TODO: normalize input so that trailing slashes can be sent in without barfing
function add_to_bash_completion($path){
    if [ -f $path ]; then
        source $path
    else if [ -d $path ]; then
        source $path/*
    fi
}

#   /usr/local/etc/bash_completion.d
#if [ -f $(brew --prefix)/etc/bash_completion ]; then
#	. $(brew --prefix)/etc/bash_completion
#fi

#   brew ( global )
add_to_bash_completion("$(brew --prefix)/etc/bash_completion")

#   brew ( extra )
add_to_bash_completion("/usr/local/Library/Contributions/brew_bash_completion.sh")

#   vagrant
add_to_bash_completion("/usr/local/Cellar/vagrant-completion/1.7.2/etc/bash_completion.d")

#   hub ( github cli )
add_to_bash_completion("/usr/local/Cellar/hub/2.2.1/etc/bash_completion.d")

#   tarsnap
add_to_bash_completion("/Users/smacdonald/tarsnap/tarsnap-autoconf-1.0.36.1/misc/bash_completion.d")
