#!/bin/bash

#   find the first docker-machine, start it, and set appropriate environment variables
machinename="$(docker-machine ls -q | head -n 1)"
docker-machine start "$machinename"
eval "$(docker-machine env $machinename)"

