#!/bin/bash

#   find the first docker-machine poduced by docker-machine ls, start it, and set appropriate environment variables
machinename="$(docker-machine ls -q | head -n 1)"
if [ "$(docker-machine status $machinename)" != "Running" ]; then
    docker-machine start "$machinename" && eval $(docker-machine env $machinename)
else
    eval $(docker-machine env $machinename)
fi
