#!/bin/bash

GIT_DISCOVERY_ACROSS_FILESYSTEM=1
GIT_EDITOR=nvim
export GIT_DISCOVERY_ACROSS_FILESYSTEM
export GIT_EDITOR

source /etc/bash_completion.d/*git*

#	convert log history to csv
#	useful for invoices, etc
function git_make_csv() {
	git log --date=local --pretty=format:"%h%x09%an%x09%ad%x09%s" > commits.$1.tsv;
};
