#!/bin/bash

export GIT_DISCOVERY_ACROSS_FILESYSTEM=1

#	bash completion
source ~/.git-completion.bash

#	helper functions
##	convert log history to csv
function git_make_csv() {
	git log --date=local --pretty=format:"%h%x09%an%x09%ad%x09%s" > commits.local.tsv;
};
