#!/bin/bash

# The next line updates PATH for the Google Cloud SDK.
dotfiles_add2path ~/google-cloud-sdk/bin

# The next line enables bash completion for gcloud.
source ~/google-cloud-sdk/completion.bash.inc
