#!/bin/bash

GPG_TTY=$(tty)
export GPG_TTY

alias gpg=gpg2

function gpg_restart_agent(){
   killall gpg-agent && eval $(gpg-agent --daemon)
}

if [ $(uname) = "Darwin" ]; then
    dotfiles_add2path /usr/local/MacGPG2/bin
fi

if [[ -n "$SSH_CONNECTION" ]] ;then
    export PINENTRY_USER_DATA="USE_CURSES=1"
fi
