#!/usr/bin/env bash

##	exit normally if minikube is not running


##	if minikube _is_ running, do this
minikube status 1> /dev/null 2> /dev/null && eval $(minikube docker-env)
eval $(kubectl completion bash)
alias k=kubectl
alias m=minikube
