#!/usr/bin/env bash

#   Mac OS tweaks

##  key repeat
defaults write NSGlobalDomain KeyRepeat -int 0
defaults write -g InitialKeyRepeat -int 15
defaults write -g KeyRepeat -int 2

##  Some sort of completion
# Add tab completion for `defaults read|write NSGlobalDomain`
# You could just use `-g` instead, but I like being explicit
complete -W "NSGlobalDomain" defaults

##  Screenshots
### Save screenshots to the desktop
defaults write com.apple.screencapture location -string "${HOME}/Desktop"
### Save screenshots in PNG format (other options: BMP, GIF, JPG, PDF, TIFF)
defaults write com.apple.screencapture type -string "png"
#### Disable shadow in screenshots
defaults write com.apple.screencapture disable-shadow -bool true
