#!/bin/bash

function start_pap() {
	ROOT=~/repos/katana/pap
	cd $ROOT
	( $ROOT/start_server.sh ) &
	( $ROOT/start_client.sh ) &
	( $ROOT/scripts/local/tunnels/database_stage.sh ) &
	wait
	notify-send "cool" "beans"
}
