#!/bin/bash

function open_tunnel() {
	ssh -N -T -f ujump
};

function close_tunnel() {
	pid="$(pgrep -f ujump)";
	kill $pid;
};

function start_pap() {
	cd ~/repos/katana/pap
	./start_server &
	./start_client &
}

