#!/bin/bash

function start_pap() {
	ROOT=~/repos/katana/pap
	cd $ROOT
	( $ROOT/start_server.sh ) &
	( $ROOT/start_client.sh ) &
	( $ROOT/scripts/local/tunnels/database_stage.sh ) &
	wait
	notify-send "cool" "beans"
}

function kill_pap() {
	sudo pkill gulp;
	sudo pkill node;
	sudo fuser -k 6440/tcp;
	sudo fuser -k 6441/tcp;
	sudo fuser -k 6442/tcp;
	sudo fuser -k 6443/tcp;
}
