#!/bin/bash

#   commands necessary to make dotfiles work

alias dotfiles_reload='source ~/.dotfiles/bootstrap $PWD'

function dotfiles_add2path(){
    newdirectory="$1"
    position="$2"
    PATH="$(node ~/.dotfiles/cli/add2path.js $PATH $newdirectory $position)"
}
